spring:
  application:
    name: aquasmart-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/aquasmart
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aquasmart-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.aquasmart: DEBUG
  file:
    name: logs/aquasmart.log
